name: Docker CD                                    # Имя workflow

on:
  push:                                            # Запускать при push
    branches: [ "main" ]                           # Только в main
  workflow_dispatch:                               # И вручную через интерфейс

jobs:
  docker:                                          # Имя job'а
    runs-on: ubuntu-latest                         # Агент: Ubuntu

    steps:
      - uses: actions/checkout@v4                    # Получаем код

      - name: Docker login
        uses: docker/login-action@v3                 # Логинимся в Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Логин из Secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Токен из Secrets

      - name: Build and push
        uses: docker/build-push-action@v6            # Собираем и пушим образ
        with:
          file: Dockerfile
          context: .                                 # Контекст сборки (корень репо)
          push: true                                 # Публиковать в реестр
          tags: |                                    # Теги образа
            ${{ secrets.DOCKERHUB_USERNAME }}/testproject-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/testproject-api:${{ github.sha }}